### ISSUE TITLE
Power Point Report

### ISSUE THREAD

**Issue by AlexBoganova** [mottmacdonaldglobal/Report-Tool#6]
Is there a way to adjust pictures scale and pages layout?

Would be also cool if in the future, it could be not only a Word export, but maybe PP or PDF with MM templates. (Templates issue has already been raised in another topic)

To structure the export doc and find differentiate the files, is it possible to create groups / sections with different headings? This way, the export is fully prepared for a refine reporting. 

Thanks team!

**Comment by sonomirco** [comment]
So @AlexBoganova  we can expose some parameters to make the layout table adjustable the number of columns, and the number of rows per page.

For scaling the picture, we can expose a scaling factor parameter, but it will be globally applied to all the pictures, is this what are you looking for?

We can't convert a doc into a PDF because we need Word installed into the machine, and we can't install Word into the virtual machine, so for PDF you have to create it opening the doc generate 😁

Instead, we can create PowerPoint 🥳

Regarding the template, we were thing 2 ways:
1. the tool will generate a doc with the pictures and the descriptions organized based on the table, and you can add later the title, paragraphers, etc etc.
2. you will feed the tool with a template and it will be filled.

**Comment by AlexBoganova** [comment]
Haha all good. Can't see it here now, but was reading somewhere, that the tool can potentially export to PP. That would be a good option.
I just find word the most annoying format to work with images - it lives it's own life half of the time, unless you spend a good half an hour to set it all nicely, in case something needs to be changed.
