### ISSUE TITLE
Scale pictures

### ISSUE THREAD

**Issue by sonomirco** [mottmacdonaldglobal/Report-Tool#7]
So @AlexBoganova  
For scaling the picture, we can expose a scaling factor parameter, but it will be globally applied to all the pictures, is this what are you looking for?

**Comment by AlexBoganova** [comment]
Understood. Probably it'd be good to have manual control over the scale, at least for the whole batch.
Since it's hard to make it with different scaling for some images, perhaps it can be done in several goes and the merging the docs together. 
Or can we continue the same doc in a separate bath, @sonomirco ?

**Comment by sonomirco** [comment]
Do you mean,  every page is a batch, and you change the scale for each picture on a page?
I have to check the options that we can have when inserting the picture in the table, and see what is the best solution.

**Comment by sonomirco** [comment]
I think we can close this issue, implementing the use of the templates will solve this request.
